const FETCH_POSTS = "FETCH_POSTS";
const CHANGE_LOADING = "CHANGE_LOADING";
const CHANGE_ITEMS = "CHANGE_ITEMS";
const CHANGE_LIKE_ITEM = "CHANGE_LIKE_ITEM";
const DELETE_ITEM = "DELETE_ITEM";
const GET_SESSION_STORAGE_ITEMS = "GET_SESSION_STORAGE_ITEMS";
const SORT_ARRAY = "SORT_ARRAY";

export {
  FETCH_POSTS,
  CHANGE_LOADING,
  CHANGE_ITEMS,
  CHANGE_LIKE_ITEM,
  DELETE_ITEM,
  GET_SESSION_STORAGE_ITEMS,
  SORT_ARRAY,
};
